src/App.js, src/Categories/index.js, src/Crafts/Craft/index.js, src/Crafts/Craft/queries.js, src/Crafts/index.js, src/Crafts/queries.js, src/Home/index.js
Implements a call to the crafts endpoint to render a button for each craft and a call to the craft endpoint to get the craft details to display
=> LOOFAH-36 Implements craft APIs

package-lock.json, package.json, src/App.css, src/App.js, src/Categories/index.js, src/Crafts/index.js, src/Grades/index.js, src/Home/index.js, src/Skills/index.js, src/Skills/queries.js
Adds material UI and lodash.
Note that we are currently only displaying grade and category IDs in the chip components as we are waiting for LOOFAH-47 and LOOFAH-49 to add the whole objects to skills endpoint.
=> LOOFAH-43: Implements all skills on home page with nav bar and header

src/Grades/index.js, src/Home/index.js, src/Skills/index.js
=> LOOFAH-39 Implements filtering by grade

src/Categories/index.js, src/Grades/index.js, src/Home/index.js, src/Skills/index.js
Implements filtering by category
=> LOOFAH-40 filter by category

src/Crafts/index.js, src/Home/index.js, src/index.js
=> LOOFAH-41: Implements filtering by craft

package-lock.json, package.json, src/Categories/queries.js, src/Crafts/Craft/queries.js, src/Crafts/queries.js, src/Grades/queries.js, src/Skills/queries.js, src/index.js
=> LOOFAH-62: Implements apollo cache

src/Categories/index.js, src/Crafts/index.js, src/Grades/index.js, src/Skills/index.js, src/Skills/queries.js, src/index.js
=> LFH-55: Changes filtering to use titles

README.md, src/Skills/queries.js
Rebased version of https://github.com/Caitlin-cooling/loofah-frontend/pull/24
=> LFH-59: Changes queries to use titles

src/App.js, src/Home/index.js
Styling changes including the colour of the app bar and making the side nav sticky with a scroll
=> LFH-58: Styling changes

.eslintrc.js, package-lock.json, src/App.js, src/Categories/__tests__/index.spec.js, src/Categories/index.js, src/Categories/queries.js, src/Config/config.js, src/Crafts/Craft/index.js, src/Crafts/Craft/queries.js, src/Crafts/index.js, src/Crafts/queries.js, src/Grades/index.js, src/Grades/queries.js, src/Home/__tests__/index.spec.js, src/Home/index.js, src/Skills/__tests__/index.spec.js, src/Skills/index.js, src/Skills/queries.js, src/index.css, src/index.js, src/serviceWorker.js, src/setupTests.js, src/utils/__tests__/formatters.spec.js, src/utils/formatters.js
Implements grouping by title util function.
Changes strings to use double quotes.
=> LFH-56 group by title

src/Grades/index.js, src/Home/index.js, src/Skills/SimpleAccordion.js, src/Skills/__tests__/index.spec.js, src/Skills/queries.js, src/utils/__tests__/formatters.spec.js, src/utils/formatters.js
Query changes:
- Changes skill title to topic
- Changes gradeTitle to gradeTitles
=> LFH-77 changes skill title to topic and gradeTitle to gradeTitles

src/Home/index.js
Updates header and removes selectedGrade logic
=> LFH-68 Updates header

src/Categories/index.js, src/Home/index.js
Updated Categories component:
- Used Tabs component from Material ui to reformat component
=> LFH-72: Categories changed to navigation tabs

src/pages/Skills/SkillsList/SimpleAccordion/index.js, src/queries/skill.queries.js
PR raised against LFH-98 skills page
This needs a bit of work, but thought maybe we could merge so everything still kind of works, then tidy up on https://devservices.jira.com/browse/LFH-103 ?
=> LFH-102 Update skill list to use headline from skill object

src/components/ChipGroup/index.js, src/pages/Skills/SkillsList/SimpleAccordion/index.js, src/pages/Skills/index.js, src/queries/skill.queries.js
=> LFH-104 adds chips to skills

src/pages/Skills/SkillsList/SimpleAccordion/index.js, src/pages/Skills/index.js
=> LFH-121 Fixes spacing defect

src/pages/Skills/SkillsList/SimpleAccordion/index.js, src/pages/Skills/index.js
Ticket: https://devservices.jira.com/browse/LFH-103
Added description to each skill (if it exists) and updated the styling.
=> LFH-103-added skill description and added styling

src/App.css, src/App.js, src/pages/CareerFaqs/index.js
=> LFH-130 Adds career FAQs page

package-lock.json, package.json, src/App.js, src/pages/Pathway/index.js, src/pages/Skills/index.js
=> LFH-129 see more links

package-lock.json, package.json, src/App.js, src/components/TabGroup/index.js, src/pages/CareerFaqs/index.js, src/pages/Pathway/index.js, src/pages/Skills/index.js
=> LFH-128 Implements engineering career page

src/App.js, src/components/LoofahLink/index.js, src/data/crafts.js, src/pages/Crafts/index.js, src/pages/Pathway/index.js, src/pages/Skills/index.js
=> LFH-100 Adds crafts page

src/components/ChipGroup/index.js, src/pages/Pathway/index.js, src/pages/Skills/GradeDescriptions.js, src/pages/Skills/SkillsList/index.js, src/pages/Skills/index.js
https://devservices.jira.com/browse/LFH-136
=> LFH-136 Implements link filtering
